### ISSUE TITLE
Rule break - mmap and pthreads are not part of the C standard library

### ISSUE THREAD

**Issue by kohsh** [dannyvankooten/1brc#11]
First rule from https://1brc.dev/ : No external library dependencies may be used. That means no lodash, no numpy, no Boost, no nothing. You're limited to the standard library of your language.

I understand that this just comes with the territory when attempting this challenge in C, but the provided solutions in this repro that rely on posix (let alone some linux header references sprinkled in) are technically rules breaks.

Might be a good thing to note in the readme, at the least.

**Comment by dannyvankooten** [comment]
This repository predates that website and rules. Not sure who is behind that site, but this experiment was based off of the original 1BRC challenge as posed by Gunnar, just in C instead of Java.
