### ISSUE TITLE
OSX: warning: unknown warning option '-Wtrampolines'

### ISSUE THREAD

**Issue by Grabber** [dannyvankooten/1brc#3]
```
lvmc@Luizs-MacBook-Pro 1brc % make      
mkdir -p bin/
cc -O2 -march=native -Wall -Wextra -Wpedantic -Wformat=2 -Wconversion -Wtrampolines -Wimplicit-fallthrough create-sample.c -lm -o bin/create-sample
warning: unknown warning option '-Wtrampolines' [-Wunknown-warning-option]
1 warning generated.
cc -O2 -march=native -Wall -Wextra -Wpedantic -Wformat=2 -Wconversion -Wtrampolines -Wimplicit-fallthrough analyze.c -o bin/analyze
warning: unknown warning option '-Wtrampolines' [-Wunknown-warning-option]
1 warning generated.
```

**Comment by dannyvankooten** [comment]
-Wtrampolines is a flag that only gcc13 or later supports. Clang doesn’t. You can safely ignore it, we can probably remove it from $CFLAGS altogether.Op 8 jan. 2024 om 15:07 heeft Luiz Vitor Martinez Cardoso ***@***.***> het volgende geschreven:﻿
***@***.*** 1brc % make      
mkdir -p bin/
cc -O2 -march=native -Wall -Wextra -Wpedantic -Wformat=2 -Wconversion -Wtrampolines -Wimplicit-fallthrough create-sample.c -lm -o bin/create-sample
warning: unknown warning option '-Wtrampolines' [-Wunknown-warning-option]
1 warning generated.
cc -O2 -march=native -Wall -Wextra -Wpedantic -Wformat=2 -Wconversion -Wtrampolines -Wimplicit-fallthrough analyze.c -o bin/analyze
warning: unknown warning option '-Wtrampolines' [-Wunknown-warning-option]
1 warning generated.
